# Generated by Django 2.2.7 on 2019-11-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('text', models.TextField(max_length=2000, verbose_name='本文')),
                ('create_date', models.DateTimeField(verbose_name='日時')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
