# Generated by Django 2.2.7 on 2019-11-20 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='日時'),
        ),
    ]
