# Generated by Django 2.2.7 on 2019-11-21 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_update_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('programming', 'Programming'), ('travel', 'Travel'), ('workout', 'Workout')], max_length=50, verbose_name='ジャンル')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='記事')),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
